version: "3" # 파일 규격 버전
services: 
  db: # 서비스 명
    image: mysql:5.7.28 
    container_name: mysql-5.7.28 
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # 환경병수 설정
      MYSQL_ROOT_PASSWORD: "micehub@100"  
    command: # 기본 명령 변경.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql 

#  jdk8: 
#      image: openjdk:8u212-jdk 
#      container_name: jdk8 
#      restart: always 

  tomcat8:    
      image: tomcat:7
      container_name: tomcat
      environment:
        - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
      command: /usr/local/tomcat/bin/catalina.sh jpda run
      ports:
        - "80:8080"
        - "8000:8000"
      volumes:
        - ../MiceHub_v21/WebContent:/usr/local/tomcat/webapps/ROOT
        - ./logs:/usr/local/tomcat/logs
        - ./tomcat7-config:/usr/local/tomcat/conf:rw
      links:
        - db
      restart: always        
  
